db:
  image: postgres:9.4.5

  volumes:
    - docker-example-postgres:/var/lib/postgresql/data

web:
  build: .
  ports:
    - '3000:3000'
  env_file: .env
  environment:
    RAILS_ENV: development
  volumes:
    - './:/var/app'
  working_dir: /var/app
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  links:
    - db
